export interface Country {
  code: string
  zh: string
  en: string
}

export interface CountryGroup {
  key: string
  zh: string
  en: string
  countries: Country[]
}

export const COUNTRY_GROUPS: CountryGroup[] = [
  {
    key: "east-asia",
    zh: "东亚",
    en: "East Asia",
    countries: [
      { code: "cn", zh: "中国", en: "China" },
      { code: "hk", zh: "中国香港", en: "Hong Kong SAR, China" },
      { code: "tw", zh: "中国台湾", en: "Taiwan, China" },
      { code: "mo", zh: "中国澳门", en: "Macao SAR, China" },
      { code: "jp", zh: "日本", en: "Japan" },
      { code: "kr", zh: "韩国", en: "South Korea" },
      { code: "kp", zh: "朝鲜", en: "North Korea" },
      { code: "mn", zh: "蒙古", en: "Mongolia" },
    ],
  },
  {
    key: "southeast-asia",
    zh: "东南亚",
    en: "Southeast Asia",
    countries: [
      { code: "sg", zh: "新加坡", en: "Singapore" },
      { code: "my", zh: "马来西亚", en: "Malaysia" },
      { code: "th", zh: "泰国", en: "Thailand" },
      { code: "vn", zh: "越南", en: "Vietnam" },
      { code: "ph", zh: "菲律宾", en: "Philippines" },
      { code: "id", zh: "印度尼西亚", en: "Indonesia" },
      { code: "mm", zh: "缅甸", en: "Myanmar" },
      { code: "kh", zh: "柬埔寨", en: "Cambodia" },
      { code: "la", zh: "老挝", en: "Laos" },
      { code: "bn", zh: "文莱", en: "Brunei" },
      { code: "tl", zh: "东帝汶", en: "Timor-Leste" },
    ],
  },
  {
    key: "south-asia",
    zh: "南亚",
    en: "South Asia",
    countries: [
      { code: "in", zh: "印度", en: "India" },
      { code: "pk", zh: "巴基斯坦", en: "Pakistan" },
      { code: "bd", zh: "孟加拉国", en: "Bangladesh" },
      { code: "lk", zh: "斯里兰卡", en: "Sri Lanka" },
      { code: "np", zh: "尼泊尔", en: "Nepal" },
      { code: "bt", zh: "不丹", en: "Bhutan" },
      { code: "mv", zh: "马尔代夫", en: "Maldives" },
      { code: "af", zh: "阿富汗", en: "Afghanistan" },
    ],
  },
  {
    key: "central-west-asia",
    zh: "中亚/西亚",
    en: "Central & West Asia",
    countries: [
      { code: "ae", zh: "阿联酋", en: "United Arab Emirates" },
      { code: "sa", zh: "沙特阿拉伯", en: "Saudi Arabia" },
      { code: "tr", zh: "土耳其", en: "Turkey" },
      { code: "il", zh: "以色列", en: "Israel" },
      { code: "qa", zh: "卡塔尔", en: "Qatar" },
      { code: "kw", zh: "科威特", en: "Kuwait" },
      { code: "bh", zh: "巴林", en: "Bahrain" },
      { code: "om", zh: "阿曼", en: "Oman" },
      { code: "jo", zh: "约旦", en: "Jordan" },
      { code: "lb", zh: "黎巴嫩", en: "Lebanon" },
      { code: "iq", zh: "伊拉克", en: "Iraq" },
      { code: "ir", zh: "伊朗", en: "Iran" },
      { code: "sy", zh: "叙利亚", en: "Syria" },
      { code: "ye", zh: "也门", en: "Yemen" },
      { code: "ps", zh: "巴勒斯坦", en: "Palestine" },
      { code: "cy", zh: "塞浦路斯", en: "Cyprus" },
      { code: "ge", zh: "格鲁吉亚", en: "Georgia" },
      { code: "am", zh: "亚美尼亚", en: "Armenia" },
      { code: "az", zh: "阿塞拜疆", en: "Azerbaijan" },
      { code: "kz", zh: "哈萨克斯坦", en: "Kazakhstan" },
      { code: "uz", zh: "乌兹别克斯坦", en: "Uzbekistan" },
      { code: "tm", zh: "土库曼斯坦", en: "Turkmenistan" },
      { code: "kg", zh: "吉尔吉斯斯坦", en: "Kyrgyzstan" },
      { code: "tj", zh: "塔吉克斯坦", en: "Tajikistan" },
    ],
  },
  {
    key: "europe",
    zh: "欧洲",
    en: "Europe",
    countries: [
      { code: "gb", zh: "英国", en: "United Kingdom" },
      { code: "de", zh: "德国", en: "Germany" },
      { code: "fr", zh: "法国", en: "France" },
      { code: "it", zh: "意大利", en: "Italy" },
      { code: "es", zh: "西班牙", en: "Spain" },
      { code: "pt", zh: "葡萄牙", en: "Portugal" },
      { code: "nl", zh: "荷兰", en: "Netherlands" },
      { code: "be", zh: "比利时", en: "Belgium" },
      { code: "lu", zh: "卢森堡", en: "Luxembourg" },
      { code: "ch", zh: "瑞士", en: "Switzerland" },
      { code: "at", zh: "奥地利", en: "Austria" },
      { code: "ie", zh: "爱尔兰", en: "Ireland" },
      { code: "dk", zh: "丹麦", en: "Denmark" },
      { code: "se", zh: "瑞典", en: "Sweden" },
      { code: "no", zh: "挪威", en: "Norway" },
      { code: "fi", zh: "芬兰", en: "Finland" },
      { code: "is", zh: "冰岛", en: "Iceland" },
      { code: "pl", zh: "波兰", en: "Poland" },
      { code: "cz", zh: "捷克", en: "Czech Republic" },
      { code: "sk", zh: "斯洛伐克", en: "Slovakia" },
      { code: "hu", zh: "匈牙利", en: "Hungary" },
      { code: "ro", zh: "罗马尼亚", en: "Romania" },
      { code: "bg", zh: "保加利亚", en: "Bulgaria" },
      { code: "hr", zh: "克罗地亚", en: "Croatia" },
      { code: "si", zh: "斯洛文尼亚", en: "Slovenia" },
      { code: "rs", zh: "塞尔维亚", en: "Serbia" },
      { code: "ba", zh: "波黑", en: "Bosnia and Herzegovina" },
      { code: "me", zh: "黑山", en: "Montenegro" },
      { code: "mk", zh: "北马其顿", en: "North Macedonia" },
      { code: "al", zh: "阿尔巴尼亚", en: "Albania" },
      { code: "xk", zh: "科索沃", en: "Kosovo" },
      { code: "gr", zh: "希腊", en: "Greece" },
      { code: "ee", zh: "爱沙尼亚", en: "Estonia" },
      { code: "lv", zh: "拉脱维亚", en: "Latvia" },
      { code: "lt", zh: "立陶宛", en: "Lithuania" },
      { code: "ua", zh: "乌克兰", en: "Ukraine" },
      { code: "by", zh: "白俄罗斯", en: "Belarus" },
      { code: "md", zh: "摩尔多瓦", en: "Moldova" },
      { code: "ru", zh: "俄罗斯", en: "Russia" },
      { code: "mt", zh: "马耳他", en: "Malta" },
      { code: "mc", zh: "摩纳哥", en: "Monaco" },
      { code: "li", zh: "列支敦士登", en: "Liechtenstein" },
      { code: "ad", zh: "安道尔", en: "Andorra" },
      { code: "sm", zh: "圣马力诺", en: "San Marino" },
      { code: "va", zh: "梵蒂冈", en: "Vatican City" },
    ],
  },
  {
    key: "north-america",
    zh: "北美洲",
    en: "North America",
    countries: [
      { code: "us", zh: "美国", en: "United States" },
      { code: "ca", zh: "加拿大", en: "Canada" },
      { code: "mx", zh: "墨西哥", en: "Mexico" },
      { code: "gt", zh: "危地马拉", en: "Guatemala" },
      { code: "bz", zh: "伯利兹", en: "Belize" },
      { code: "sv", zh: "萨尔瓦多", en: "El Salvador" },
      { code: "hn", zh: "洪都拉斯", en: "Honduras" },
      { code: "ni", zh: "尼加拉瓜", en: "Nicaragua" },
      { code: "cr", zh: "哥斯达黎加", en: "Costa Rica" },
      { code: "pa", zh: "巴拿马", en: "Panama" },
      { code: "cu", zh: "古巴", en: "Cuba" },
      { code: "jm", zh: "牙买加", en: "Jamaica" },
      { code: "ht", zh: "海地", en: "Haiti" },
      { code: "do", zh: "多米尼加", en: "Dominican Republic" },
      { code: "tt", zh: "特立尼达和多巴哥", en: "Trinidad and Tobago" },
      { code: "bb", zh: "巴巴多斯", en: "Barbados" },
      { code: "bs", zh: "巴哈马", en: "Bahamas" },
      { code: "ag", zh: "安提瓜和巴布达", en: "Antigua and Barbuda" },
      { code: "dm", zh: "多米尼克", en: "Dominica" },
      { code: "gd", zh: "格林纳达", en: "Grenada" },
      { code: "kn", zh: "圣基茨和尼维斯", en: "Saint Kitts and Nevis" },
      { code: "lc", zh: "圣卢西亚", en: "Saint Lucia" },
      { code: "vc", zh: "圣文森特和格林纳丁斯", en: "Saint Vincent and the Grenadines" },
    ],
  },
  {
    key: "south-america",
    zh: "南美洲",
    en: "South America",
    countries: [
      { code: "br", zh: "巴西", en: "Brazil" },
      { code: "ar", zh: "阿根廷", en: "Argentina" },
      { code: "cl", zh: "智利", en: "Chile" },
      { code: "co", zh: "哥伦比亚", en: "Colombia" },
      { code: "pe", zh: "秘鲁", en: "Peru" },
      { code: "ve", zh: "委内瑞拉", en: "Venezuela" },
      { code: "ec", zh: "厄瓜多尔", en: "Ecuador" },
      { code: "bo", zh: "玻利维亚", en: "Bolivia" },
      { code: "py", zh: "巴拉圭", en: "Paraguay" },
      { code: "uy", zh: "乌拉圭", en: "Uruguay" },
      { code: "gy", zh: "圭亚那", en: "Guyana" },
      { code: "sr", zh: "苏里南", en: "Suriname" },
    ],
  },
  {
    key: "oceania",
    zh: "大洋洲",
    en: "Oceania",
    countries: [
      { code: "au", zh: "澳大利亚", en: "Australia" },
      { code: "nz", zh: "新西兰", en: "New Zealand" },
      { code: "pg", zh: "巴布亚新几内亚", en: "Papua New Guinea" },
      { code: "fj", zh: "斐济", en: "Fiji" },
      { code: "sb", zh: "所罗门群岛", en: "Solomon Islands" },
      { code: "vu", zh: "瓦努阿图", en: "Vanuatu" },
      { code: "ws", zh: "萨摩亚", en: "Samoa" },
      { code: "to", zh: "汤加", en: "Tonga" },
      { code: "ki", zh: "基里巴斯", en: "Kiribati" },
      { code: "fm", zh: "密克罗尼西亚", en: "Micronesia" },
      { code: "mh", zh: "马绍尔群岛", en: "Marshall Islands" },
      { code: "pw", zh: "帕劳", en: "Palau" },
      { code: "nr", zh: "瑙鲁", en: "Nauru" },
      { code: "tv", zh: "图瓦卢", en: "Tuvalu" },
    ],
  },
  {
    key: "africa",
    zh: "非洲",
    en: "Africa",
    countries: [
      { code: "za", zh: "南非", en: "South Africa" },
      { code: "eg", zh: "埃及", en: "Egypt" },
      { code: "ng", zh: "尼日利亚", en: "Nigeria" },
      { code: "ke", zh: "肯尼亚", en: "Kenya" },
      { code: "et", zh: "埃塞俄比亚", en: "Ethiopia" },
      { code: "gh", zh: "加纳", en: "Ghana" },
      { code: "tz", zh: "坦桑尼亚", en: "Tanzania" },
      { code: "ma", zh: "摩洛哥", en: "Morocco" },
      { code: "dz", zh: "阿尔及利亚", en: "Algeria" },
      { code: "tn", zh: "突尼斯", en: "Tunisia" },
      { code: "ly", zh: "利比亚", en: "Libya" },
      { code: "sd", zh: "苏丹", en: "Sudan" },
      { code: "ss", zh: "南苏丹", en: "South Sudan" },
      { code: "cd", zh: "刚果（金）", en: "DR Congo" },
      { code: "cg", zh: "刚果（布）", en: "Republic of the Congo" },
      { code: "cm", zh: "喀麦隆", en: "Cameroon" },
      { code: "ci", zh: "科特迪瓦", en: "Ivory Coast" },
      { code: "sn", zh: "塞内加尔", en: "Senegal" },
      { code: "ml", zh: "马里", en: "Mali" },
      { code: "bf", zh: "布基纳法索", en: "Burkina Faso" },
      { code: "ne", zh: "尼日尔", en: "Niger" },
      { code: "td", zh: "乍得", en: "Chad" },
      { code: "gn", zh: "几内亚", en: "Guinea" },
      { code: "rw", zh: "卢旺达", en: "Rwanda" },
      { code: "bi", zh: "布隆迪", en: "Burundi" },
      { code: "ug", zh: "乌干达", en: "Uganda" },
      { code: "mz", zh: "莫桑比克", en: "Mozambique" },
      { code: "mg", zh: "马达加斯加", en: "Madagascar" },
      { code: "ao", zh: "安哥拉", en: "Angola" },
      { code: "zm", zh: "赞比亚", en: "Zambia" },
      { code: "zw", zh: "津巴布韦", en: "Zimbabwe" },
      { code: "bw", zh: "博茨瓦纳", en: "Botswana" },
      { code: "na", zh: "纳米比亚", en: "Namibia" },
      { code: "sz", zh: "斯威士兰", en: "Eswatini" },
      { code: "ls", zh: "莱索托", en: "Lesotho" },
      { code: "mw", zh: "马拉维", en: "Malawi" },
      { code: "mu", zh: "毛里求斯", en: "Mauritius" },
      { code: "sc", zh: "塞舌尔", en: "Seychelles" },
      { code: "dj", zh: "吉布提", en: "Djibouti" },
      { code: "er", zh: "厄立特里亚", en: "Eritrea" },
      { code: "so", zh: "索马里", en: "Somalia" },
      { code: "lr", zh: "利比里亚", en: "Liberia" },
      { code: "sl", zh: "塞拉利昂", en: "Sierra Leone" },
      { code: "tg", zh: "多哥", en: "Togo" },
      { code: "bj", zh: "贝宁", en: "Benin" },
      { code: "mr", zh: "毛里塔尼亚", en: "Mauritania" },
      { code: "gm", zh: "冈比亚", en: "Gambia" },
      { code: "gw", zh: "几内亚比绍", en: "Guinea-Bissau" },
      { code: "cv", zh: "佛得角", en: "Cape Verde" },
      { code: "st", zh: "圣多美和普林西比", en: "São Tomé and Príncipe" },
      { code: "gq", zh: "赤道几内亚", en: "Equatorial Guinea" },
      { code: "ga", zh: "加蓬", en: "Gabon" },
      { code: "cf", zh: "中非", en: "Central African Republic" },
      { code: "km", zh: "科摩罗", en: "Comoros" },
    ],
  },
]

/** Flat lookup: code → Country */
export const COUNTRY_MAP = new Map<string, Country & { groupKey: string }>(
  COUNTRY_GROUPS.flatMap((g) =>
    g.countries.map((c) => [c.code, { ...c, groupKey: g.key }])
  )
)
